spring:
  application:
    name: SistemaDeFacturacion

  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect  

  thymeleaf:
    cache: false

  jwt:
    secret: mi_super_clave_secreta_para_jwt_123456789
    expiration-ms: 3600000  # 1 hora en milisegundos
